- name: -> Get a list of all NetBackup Roles
  uri:
    url: https://{{ nbu_api_hostname}}:1556/netbackup/access-control/roles
    method: GET
    headers:
      Content-Type: "{{ nbu_api_content_type }}"
      Authorization: "{{ NBU_APIKEY }}"        
    body_format: json
    status_code: 200, 201, 400, 401, 409, 415, 500
    validate_certs: no
  register: list_of_rbac_roles
  tags:
    - get_api_key

- name: -> Obtain the ID of the specific NetBackup Role
  set_fact:
    role_id: "{{ lookup('template', 'get_role_id.j2') | trim }}"
  register: rbac_role_id




