
- name: -> Create NetBackup Universal Share
  uri:
    url: https://{{ nbu_api_hostname }}:1556/netbackup/storage/storage-servers/{{ nbu_us_ssid }}/universal-shares
    method: POST
    headers:
      Content-Type: "{{ nbu_api_content_type }}"
      Authorization: "{{ NBU_API_KEY }}"      
    body: "{{ lookup('template', 'nbu_us_create.j2') }}"
    body_format: json
    validate_certs: False
    timeout: "300"
    status_code:
      - 200
      - 201
      - 400
      - 401
      - 404
      - 405
      - 409
      - 500
  register: result
  changed_when: result.status != 409
  failed_when: result.status not in [201, 201, 409, 500, 7427]
  retries: 5
  delay: 2
  until:  result.status == 201 or result.status == 409 or result.status == 500 or result.status == 7427
  ignore_errors: true
  tags:
    - nbu_api_unishare_create


